### ISSUE TITLE
Release the .Net Framework fix

### ISSUE THREAD

**Issue by yoroto** [amzn/ion-hash-dotnet#48]
Hi,

We would like to have the fix in [PR #44](https://github.com/amzn/ion-hash-dotnet/pull/44) released to Nuget. The QLDB driver 1.0.1 release depends on it to fix [a customer reported issue](https://github.com/awslabs/amazon-qldb-driver-dotnet/issues/31).

**Comment by tgregg** [comment]
Released to NuGet in 1.0.1.
